apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taskapp
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "taskapp"
  CORS_ORIGINS: "https://taskapp.3.230.145.26.nip.io"
