apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taskapp
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "taskapp"
  CORS_ORIGINS: "https://taskapp.32.192.187.43.nip.io"
